#include <iostream>
using namespace std; 
int noOfMatchstick(int);
int main() {
  int N,unit,num,result=0;
  // input statement
  cout << "Enter a number \n";
  cin >> N;
  num = N;
  /* converting each digit of number to the number of matchsticks
     that we need to write in seven segment formats.
     Then, adding them to find the total number of matchsticks 
     we need to write that number in seven segment formats.
  */
  while(N>0)    
  {    
      unit = N%10;
      result += noOfMatchstick(unit);
      N=N/10;
  }
  // Output statement 
  cout << num << " can be generated by using " 
    << result << " matchsticks" ;
  return 0;
}

// function to return the number of matchsticks 
int noOfMatchstick(int u) 
{
  if (u == 0)  return 6;
  if (u == 1)  return 2;
  if (u == 2)  return 5;
  if (u == 3)  return 5;
  if (u == 4)  return 4;
  if (u == 5)  return 5;
  if (u == 6)  return 6;
  if (u == 7)  return 3;
  if (u == 8)  return 7; 
  if (u == 9)  return 6;
}

// Code by Shivesh Ratan 😊